require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

desc "Solve puzzle"
task :solve do
  $LOAD_PATH.unshift("#{File.dirname(__FILE__)}/lib")
  require 'wired_up'
  WiredUp.solve
end